version: "3.9"  # [obrigatório] -> versão do docker-compose

services:       # [obrigatório] -> define os containers (serviços) que vão subir
  container_samuel:   # [obrigatório] -> nome interno do serviço (pode ser qualquer nome)
    image: grafana    # [obrigatório] -> imagem que será usada (Docker Hub ou custom)
    container_name: meu_grafana  # opcional -> nome fixo do container
    
    ports:            # opcional -> só se precisar expor portas
      - "80:80"       # mapeamento de porta host:container
    
    depends_on:       # opcional -> define ordem de inicialização se depender de outro serviço
      - app
    
    restart: always   # opcional -> política de restart do container. 
									    # o comando always faz sempre o container startar com o sistema op.
    volumes:          # opcional -> se precisar montar volumes persistentes ou bind mounts
      - ./data:/var/lib/grafana   # exemplo: persistir dados
    
    environment:      # opcional -> variáveis de ambiente do container
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:             # opcional -> definição de volumes nomeados (caso use no serviço acima)
  data:              # nome do volume